### ISSUE TITLE
new function to add a local package

### ISSUE THREAD

**Issue by achubaty** [RevolutionAnalytics/miniCRAN#23]
Supplements adding packages from CRAN-like repo and GitHub.

Can be used with `addOldPackage(..., writePACKAGES=FALSE)` and, after a build of the package binaries on a local machine, should add the local files to the miniCRAN repo.

"local" packages here could mean package files on the local harddrive, a network location, and possibly a non-CRAN-like web location (so this would also work with prebuilt packages from Github or other site).

**Comment by achubaty** [comment]
I have an early version of this I've been using locally but it needs clean up and testing before adding a version here.

**Comment by achubaty** [comment]
@andrie Is this covered by existing functionality per #58 and #59? I'll hold off prepping my version of this for now until I either hear back from you or have a chance to test this myself.

**Comment by achubaty** [comment]
nevermind, I read that wrong. those two issues are about installing FROM a local repo not adding a local package to one.

**Comment by achubaty** [comment]
Started new branch `23-addLocalPackages` which incorporates the `24-addPackages` branch. This new branch is still a work in progress and I haven't yet done much testing.

the aim is to provide a function that takes a pre-built local package and adds it to the miniCRAN repo. The currently unimplemented `build = TRUE` argument would allow a package to be built from the local source code (i.e., after pulling from a github repo as in #50).

I hope to return to this soon

**Comment by mpettis** [comment]
Came across this, as I need the ability to push in-house built packages to the R Server, and this seems to be the path.  Is this functionality yet present, or is there another way to add locally-built packages to the miniCRAN repo?

**Comment by achubaty** [comment]
@mpettis @andrie I've fixed up the version I had started working on in the `23-addLocalPackages` branch, and added unit tests (8cd07b028b569d5a3d138dd3d0c3fbafd9e354d7).

The new function `addLocalPackage()` looks for a pre-built package in another (non-miniCRAN-repo) location and adds it to the miniCRAN repo.

I want to test this a bit more in my work environment (rather than just at home) to make sure the improved version is working in my real use case, but please take it for a spin!

**Comment by lorenzwalthert** [comment]
Great, exaclty what I was looking for. It worked fine on my MacOS Sierra. Thanks a lot @achubaty. Any idea when this is merged into master? I think it really adds a lot of value to `miniCRAN`. Maybe just one thing I that could be stated more clearly in the help file: The argument `pkgPath` does *not* contain the package directory itself, i.e. `pkgPath` and `pkgs` make up the package directory together. Maybe that is obvious but I did not get it in the first place.

**Comment by lorenzwalthert** [comment]
I just created a minimal example how it worked with one of my packages:
https://github.com/lorenzwalthert/localCran

**Comment by achubaty** [comment]
@lorenzwalthert no idea when it will be werged -- that will up to @andrie and his schedule.

good point about `pkgPath`. I've created a new issue (#85).

**Comment by lorenzwalthert** [comment]
cool. Well with regard to the merge, why don't you create a pull request after rebasing the branch upon master?

**Comment by jgbradley1** [comment]
After `addLocalPackage()` is added to master, is there an estimate/plan on **when** the new updates will be available on CRAN?

**Comment by achubaty** [comment]
I did some fixing up and have now merged this feature branch into dev. I'll defer to @andrie as gatekeeper to merge into master and submit to CRAN. Thus, @jgbradley1, I don't have a timeframe for you, but I see there are a few other small issues that should probably be resolved for the next CRAN version.

For now, you can use `devtools::install_github("RevolutionAnalytics/miniCRAN@dev)`.
