### ISSUE TITLE
write wrappers or equivalent to easily manage packages for all three OSes

### ISSUE THREAD

**Issue by achubaty** [RevolutionAnalytics/miniCRAN#24]
`addPackages`, `updatePackages`, `makeRepo`, etc. currently specify the package type as an argument.

Either:

1. Create wrappers to these functions to be able to quickly add packages for all three types (`.tar.gz`, `.zip`, `.tgz`)
2. Ensure these functions can handle a vector, e.g.,  `type=c("source", "win.binary", ...)`

I prefer the second option.

**Comment by achubaty** [comment]
@andrie I have wrapper functions I've been using for my own needs that I can clean up and add when I get some time. What's your timeline on this?

**Comment by achubaty** [comment]
@andrie updated in the `24-addPackages` branch, which I brnached off of master this morning.

**Comment by andrie** [comment]
@achubaty Thanks for doing this. Do we need additional documentation and/or tests?
