### ISSUE TITLE
Inconsistent use of Rversion argument in addPackages

### ISSUE THREAD

**Issue by andrie** [RevolutionAnalytics/miniCRAN#42]
The use of the `Rversion=...` argument in `addPackages()` is inconsistent with use elsewhere in package, particularly `makeRepo()`

**Comment by achubaty** [comment]
Option 3 above is the easiest for the user, so I've gone ahead with that. We can convert to to an `R_system_version` under the hood to make version string comparisons.

Note that I'm only making the changes to the documentation -- the functions using `Rversion`  (namely, `twodigitRversion`) will still work if specified using the other approaches.

See the `42-rversion` branch, which was branched from `master` this morning.

**Comment by andrie** [comment]
I merged this branch `24-addPackages` into dev
