### ISSUE TITLE
Return paths from makeRepo

### ISSUE THREAD

**Issue by csgillespie** [RevolutionAnalytics/miniCRAN#65]
It would be helpful (from a git point of view) to have the package paths returned by `makeRepo`.  I think adding the line

```
## Is this OK for windows?
invisible(paste(pkgPath, pkgs, sep="/"))
``` 

to the end of `makeRepo` should do the trick.

**Comment by andrie** [comment]
You should never use `paste()` to create file paths.

Use `file.path()` instead - this know how to deal with separators on different operating systems.

I like your suggestion, though.

When time allows, I really want to rethink the entire API to make it easier to use, internally consistent, and hopefully also simpler.

**Comment by csgillespie** [comment]
I knew `paste` was wrong - just couldn't remember what to use instead.

**Comment by andrie** [comment]
@csgillespie I pushed an update to the dev branch. Can you please take a look if this is what you had in mind?

**Comment by csgillespie** [comment]
Not quite. When I try:

```
R> x = makeRepo("ggplot2", path="tmp")
trying URL 'https://cran.rstudio.com/src/contrib/ggplot2_2.1.0.tar.gz'
Content type 'application/x-gzip' length 1571788 bytes (1.5 MB)
==================================================
downloaded 1.5 MB
```
I would like `x` to contain the paths, i.e. `/tmp/tmp/src/contrib/ggplot2_2.1.0.tar.gz` Instead, I get

```
R> x
[[1]]
[1] 2

```

**Comment by andrie** [comment]
Did you check out the dev branch?  This isn't in master yet.  Your results indicate you're using the master branch, i.e. old behaviour.

**Comment by csgillespie** [comment]
Sorry to take so long, but this is exactly what I'm after. Thanks
