### ISSUE TITLE
NEWS page hasn't been updated since 0.2-2

### ISSUE THREAD

**Issue by sebastian-c** [RevolutionAnalytics/miniCRAN#73]
Some changes have been the move to Microsoft and fixes to documentation.

**Comment by andrie** [comment]
You can see some additional changes at the releases page.

https://github.com/RevolutionAnalytics/miniCRAN/releases/tag/v0.2.4

**Comment by sebastian-c** [comment]
I've made a pull request (#74) that partially fills in the details.

**Comment by achubaty** [comment]
can this be closed?

**Comment by andrie** [comment]
Yes - thanks for the reminder.
